version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7-fpm-browsers-legacy
    steps:
      - checkout
      - run:
          name: "Install composer"
          command: composer install --no-interaction --prefer-source
      - run:
          name: "Run tests"
          command: phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
      - run:
          name: "Upload report"
          command: bash <(curl -s https://codecov.io/bash)
